import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"

/** @type {import("eslint").Linter.Config[]} */
const config = [
  ...nextVitals,
  ...nextTs,
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "next-env.d.ts",
      // Vendored shadcn/ui output generated by v0. The four components the
      // site actually imports (button, input, label, textarea) lint clean;
      // the other 46 are unused scaffolding and not worth maintaining lint
      // fixes for. Re-generate with `npx shadcn add <name>` rather than
      // hand-editing.
      "components/ui/**",
      "hooks/**",
    ],
  },
  {
    rules: {
      // `const { company: _company, ...rest } = obj` is the idiomatic way to
      // omit a key; the discarded binding is not a mistake.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { ignoreRestSiblings: true, argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
]

export default config
